name: Multiversus
version: ${pluginVersion}
description: A Minecraft plugin where every match is a new wild party of iconic characters challenging each other in wonderfully strange ways.
author: kubbidev
website: https://kubbidev.com
main: me.kubbidev.multiversus.loader.BukkitLoaderPlugin
load: STARTUP

# Mark the plugin as 1.13 compatible to avoid CB having to perform quite as much unnecessary
# remapping when the plugin is loaded.
api-version: 1.13

commands:
  multiversus:
    description: Multiversus plugin root command
    aliases: [m]